"""Generate a self-contained random map script around a real coastline.

The coastline arrives as a ``<LAND_GENERATION>`` section from
:mod:`rwmaps.rms_land`; everything here is the ordinary random-map machinery
that makes the result playable - water depths, forests, resources and fish.

Two things that bit us and are easy to get wrong:

* ``base_terrain`` is ``WATER``, so there is no ``DEEP_WATER`` on the map until
  this script creates some. Chaining ``MED_WATER`` off ``DEEP_WATER`` (which is
  what the shipped real-world scripts do, because their ``.scx`` already
  supplies deep ocean) produces a flat, uniform sea and leaves deep-water fish
  with nowhere legal to spawn.
* Fish need water that is far enough from land. ``max_distance_to_other_zones``
  measures distance to land zones, so it only behaves if the coastline shares a
  single zone id.
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

_HEADER = """\
/* {title}
 *
 * Real-world coastline encoded as create_land blocks, so this script is
 * self-contained: no companion .scx, no game files touched, and the engine
 * transfers it to other players automatically in multiplayer.
 *
 * Generated by rwmaps -- projection {projection}, {size}x{size} tiles
 */

<PLAYER_SETUP>
  direct_placement
  ai_info_map_type {ai_map_type} 0 0 0
"""

#: Sea floor. Depth bands are grown outward from the shore so that shore fish,
#: shallow fish and deep fish each have somewhere valid to sit.
_WATER = """
<TERRAIN_GENERATION>

create_terrain MED_WATER
{
  base_terrain                   WATER
  number_of_clumps               22
  spacing_to_other_terrain_types 1
  land_percent                   40
}

create_terrain DEEP_WATER
{
  base_terrain                   MED_WATER
  number_of_clumps               12
  spacing_to_other_terrain_types 2
  land_percent                   18
}
"""

_LAND_TERRAIN = """
create_terrain {forest}
{{
  base_terrain                   {land}
  spacing_to_other_terrain_types 5
  land_percent                   {forest_percent}
  number_of_clumps               12
  set_avoid_player_start_areas
  set_scale_by_groups
}}

create_terrain {land_alt}
{{
  base_terrain                   {land}
  number_of_clumps               18
  spacing_to_other_terrain_types 0
  land_percent                   8
  set_scale_by_size
}}

create_terrain {land_alt2}
{{
  base_terrain                   {land}
  number_of_clumps               12
  spacing_to_other_terrain_types 0
  land_percent                   5
  set_scale_by_size
}}
"""

_ELEVATION = """
<ELEVATION_GENERATION>

create_elevation        {max_elevation}
{{
  base_terrain                {land}
  number_of_clumps            {elevation_clumps}
  number_of_tiles             {elevation_tiles}
  set_scale_by_groups
  set_scale_by_size
}}
"""

#: Land resources come from the stock include, which is what the shipped
#: real-world scripts use; fish are placed explicitly because the include
#: assumes a map that already has open ocean.
_OBJECTS = """
<OBJECTS_GENERATION>

#include_drs land_and_water_resources.inc 54102

create_object {tree}
{{
  number_of_objects             40
  set_gaia_object_only
  set_scaling_to_map_size
  min_distance_to_players       8
}}

create_object DEER
{{
  number_of_objects             4
  group_variance                1
  set_loose_grouping
  set_gaia_object_only
  set_place_for_every_player
  min_distance_to_players       18
  max_distance_to_players       30
}}

/* ---- fish ---------------------------------------------------------- */

create_object SHORE_FISH
{{
  number_of_objects             40
  set_scaling_to_map_size
  set_gaia_object_only
  min_distance_group_placement  4
}}

create_object FISH
{{
  number_of_objects             30
  set_scaling_to_map_size
  set_gaia_object_only
  terrain_to_place_on           MED_WATER
  min_distance_group_placement  6
}}

create_object SALMON
{{
  number_of_groups              14
  number_of_objects             3
  set_scaling_to_map_size
  set_gaia_object_only
  terrain_to_place_on           MED_WATER
  min_distance_group_placement  8
}}

create_object MARLIN1
{{
  number_of_groups              6
  number_of_objects             2
  set_scaling_to_map_size
  set_gaia_object_only
  terrain_to_place_on           DEEP_WATER
  min_distance_group_placement  10
}}
"""


@dataclass
class RmsOptions:
    """Terrain and object choices that go with a biome."""

    land: str = "GRASS"
    land_alt: str = "GRASS3"
    land_alt2: str = "DIRT3"
    forest: str = "FOREST"
    tree: str = "OAKTREE"
    forest_percent: int = 10
    max_elevation: int = 7
    elevation_clumps: int = 8
    elevation_tiles: int = 600
    elevation: bool = True


BIOME_RMS: dict[str, RmsOptions] = {
    "temperate": RmsOptions(),
    "arid": RmsOptions(land="DIRT", land_alt="DIRT3", land_alt2="GRASS3",
                       forest="PALM_DESERT", tree="PALMTREE", forest_percent=5),
    "desert": RmsOptions(land="DESERT", land_alt="DIRT", land_alt2="DIRT3",
                         forest="PALM_DESERT", tree="PALMTREE", forest_percent=4),
    "tropical": RmsOptions(land="GRASS2", land_alt="GRASS", land_alt2="GRASS3",
                           forest="JUNGLE", tree="JUNGLETREE", forest_percent=16),
    "arctic": RmsOptions(land="SNOW", land_alt="GRASS_SNOW", land_alt2="DIRT_SNOW",
                         forest="SNOW_FOREST", tree="PINETREE", forest_percent=10),
}


def build_rms(
    title: str,
    projection: str,
    size: int,
    land_section: str,
    opts: RmsOptions | None = None,
    ai_map_type: str = "COASTAL",
) -> str:
    """Render a complete, self-contained random map script."""
    opts = opts or RmsOptions()
    parts = [
        _HEADER.format(title=title, projection=projection, size=size,
                       ai_map_type=ai_map_type),
        land_section,
        _WATER,
        _LAND_TERRAIN.format(
            land=opts.land,
            land_alt=opts.land_alt,
            land_alt2=opts.land_alt2,
            forest=opts.forest,
            forest_percent=opts.forest_percent,
        ),
    ]
    if opts.elevation:
        parts.append(
            _ELEVATION.format(
                land=opts.land,
                max_elevation=opts.max_elevation,
                elevation_clumps=opts.elevation_clumps,
                elevation_tiles=opts.elevation_tiles,
            )
        )
    parts.append(_OBJECTS.format(tree=opts.tree))
    return "\n".join(parts)


def write_rms(path: str | Path, text: str) -> Path:
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    # The engine's parser wants plain ASCII with unix line endings.
    path.write_text(text, encoding="ascii", newline="\n")
    return path
