"""Generate a self-contained random map script around a real coastline.

The coastline arrives as a ``<LAND_GENERATION>`` section from
:mod:`rwmaps.rms_land`; everything here is the ordinary random-map machinery
that makes the result playable - water depths, forests, resources and fish.

Two things that bit us and are easy to get wrong:

* ``base_terrain`` is ``WATER``, so there is no ``DEEP_WATER`` on the map until
  this script creates some. Chaining ``MED_WATER`` off ``DEEP_WATER`` (which is
  what the shipped real-world scripts do, because their ``.scx`` already
  supplies deep ocean) produces a flat, uniform sea and leaves deep-water fish
  with nowhere legal to spawn.
* Fish need water that is far enough from land. ``max_distance_to_other_zones``
  measures distance to land zones, so it only behaves if the coastline shares a
  single zone id.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path

from .rms_objects import (
    ResourceFlavor,
    ThemePins,
    build_objects,
    build_player_setup,
    build_prelude,
)

_HEADER = """\
/* {title}
 *
 * Real-world coastline encoded as create_land blocks, so this script is
 * self-contained: no companion .scx, no game files touched, and the engine
 * transfers it to other players automatically in multiplayer.
 *
 * Generated by rwmaps -- projection {projection}, {size}x{size} tiles
 */
"""

#: Kept only so the legacy path below still assembles. See ``build_rms``.
_LEGACY_PLAYER_SETUP = """\

<PLAYER_SETUP>
  direct_placement
  ai_info_map_type {ai_map_type} 0 0 0
"""

#: Sea floor. Depth bands are grown outward from the shore so that shore fish,
#: shallow fish and deep fish each have somewhere valid to sit.
_WATER = """
<TERRAIN_GENERATION>

create_terrain MED_WATER
{
  base_terrain                   WATER
  number_of_clumps               22
  spacing_to_other_terrain_types 1
  land_percent                   40
}

create_terrain DEEP_WATER
{
  base_terrain                   MED_WATER
  number_of_clumps               12
  spacing_to_other_terrain_types 2
  land_percent                   18
}
"""

_LAND_TERRAIN = """
create_terrain {forest}
{{
  base_terrain                   {land}
  spacing_to_other_terrain_types 5
  land_percent                   {forest_percent}
  number_of_clumps               {forest_clumps}
  set_avoid_player_start_areas
  set_scale_by_groups
}}

create_terrain {land_alt}
{{
  base_terrain                   {land}
  number_of_clumps               18
  spacing_to_other_terrain_types 0
  land_percent                   8
  set_scale_by_size
}}

create_terrain {land_alt2}
{{
  base_terrain                   {land}
  number_of_clumps               12
  spacing_to_other_terrain_types 0
  land_percent                   5
  set_scale_by_size
}}
"""

_ELEVATION = """
<ELEVATION_GENERATION>

create_elevation        {max_elevation}
{{
  base_terrain                {land}
  number_of_clumps            {elevation_clumps}
  number_of_tiles             {elevation_tiles}
  set_scale_by_groups
  set_scale_by_size
}}
"""

#: Land resources come from the stock include, which is what the shipped
#: real-world scripts use; fish are placed explicitly because the include
#: assumes a map that already has open ocean.
_OBJECTS = """
<OBJECTS_GENERATION>

#include_drs land_and_water_resources.inc 54102

create_object {tree}
{{
  number_of_objects             40
  set_gaia_object_only
  set_scaling_to_map_size
  min_distance_to_players       8
}}

create_object DEER
{{
  number_of_objects             4
  group_variance                1
  set_loose_grouping
  set_gaia_object_only
  set_place_for_every_player
  min_distance_to_players       18
  max_distance_to_players       30
}}

/* ---- fish ---------------------------------------------------------- */

create_object SHORE_FISH
{{
  number_of_objects             40
  set_scaling_to_map_size
  set_gaia_object_only
  min_distance_group_placement  4
}}

create_object FISH
{{
  number_of_objects             30
  set_scaling_to_map_size
  set_gaia_object_only
  terrain_to_place_on           MED_WATER
  min_distance_group_placement  6
}}

create_object SALMON
{{
  number_of_groups              14
  number_of_objects             3
  set_scaling_to_map_size
  set_gaia_object_only
  terrain_to_place_on           MED_WATER
  min_distance_group_placement  8
}}

create_object MARLIN1
{{
  number_of_groups              6
  number_of_objects             2
  set_scaling_to_map_size
  set_gaia_object_only
  terrain_to_place_on           DEEP_WATER
  min_distance_group_placement  10
}}
"""

#: Supplemental gold/stone/deer/boar placed close to the TC, with no
#: ``max_distance_to_other_zones`` restriction (unlike the stock include's own
#: gold/stone) - for regions whose coastline is too narrow for
#: land_and_water_resources.inc's medium/far tiers (18-35 tiles from the
#: player) to reliably find land at all. Confirmed empirically on the shipped
#: mod's N=10 capture pass: New Zealand showed zero-stone for 67/80
#: player-samples and zero-gold for 21/80 - see MOD_STATUS.md. A first version
#: of this block covering only gold/stone eliminated both in a 10-sample
#: real-engine retest (0/10, down from ~84%/26%), but left a smaller residual
#: any-zero rate (7/10) from occasional single-instance boar/deer misses, so
#: this also backstops those two, more lightly (they were far less broken to
#: begin with - stock ranges top out at 22/30 tiles, not 35). This doesn't
#: replace the stock include's own attempts (which still run, and still
#: succeed on wide coastlines like Italy/Salish Sea) - it's a pure addition,
#: so it should only be enabled for regions confirmed to need it
#: (``RmsOptions.tight_resource_backstop``), not applied blanket, or wide
#: regions would end up with more resources than the stock balance intends.
_TIGHT_RESOURCE_BACKSTOP = """
create_object GOLD
{
  number_of_objects             6
  group_placement_radius        2
  set_tight_grouping
  set_gaia_object_only
  set_place_for_every_player
  min_distance_to_players       8
  max_distance_to_players       14
}

create_object STONE
{
  number_of_objects             6
  group_placement_radius        2
  set_tight_grouping
  set_gaia_object_only
  set_place_for_every_player
  min_distance_to_players       8
  max_distance_to_players       14
}

create_object DEER
{
  number_of_objects             2
  set_loose_grouping
  set_gaia_object_only
  set_place_for_every_player
  min_distance_to_players       8
  max_distance_to_players       16
}

create_object BOAR
{
  number_of_objects             1
  set_gaia_object_only
  set_place_for_every_player
  min_distance_to_players       8
  max_distance_to_players       14
}
"""


@dataclass
class RmsOptions:
    """Terrain and object choices that go with a biome."""

    land: str = "GRASS"
    land_alt: str = "GRASS3"
    land_alt2: str = "DIRT3"
    forest: str = "FOREST"
    tree: str = "OAKTREE"
    forest_percent: int = 10
    #: How many separate clumps the map-wide forest is broken into.
    #: Exposed as a knob (it was hardcoded at 12); the default is unchanged.
    #:
    #: NEGATIVE RESULT, recorded so it is not re-tried: raising this does
    #: **not** even out wood between players. Britain shows a large spread
    #: in "share of my nearby land that is forest" - and it barely moves
    #: with clump count (one sample each, Britain, everything else fixed):
    #:
    #: | clumps | forest share across the 8 players |
    #: |--------|-----------------------------------|
    #: | 12     | 0.07 - 0.53                       |
    #: | 30     | 0.01 - 0.43                       |
    #: | 60     | 0.06 - 0.52                       |
    #:
    #: The cause is upstream: ``land_percent`` is a share of the *whole
    #: map's* land, and on a fragmented region players have very different
    #: amounts of land near them, so a single clump dominates the share of
    #: whoever is on a small island. Granularity cannot fix a denominator
    #: problem.
    #:
    #: The stock answer is ``includes/forest.inc``, which budgets a forest
    #: per player (``PLAYER_FOREST_TILES``, ``PLAYER_FOREST_AVOIDANCE``,
    #: ``PLAYER_FOREST_TEAM_DEDUCTION``). It builds off a per-player
    #: ``SPAWN_PLACEHOLDER`` terrain that ``rms_land`` does not paint, so
    #: adopting it is a land-generation change rather than a resource one.
    forest_clumps: int = 12
    max_elevation: int = 7
    elevation_clumps: int = 8
    elevation_tiles: int = 600
    elevation: bool = True

    #: Legacy only - the additive close-range gold/stone/deer/boar block
    #: that backstopped the 1999 include's silent placement failures. It has
    #: no meaning under System A, which fixes the cause rather than papering
    #: over it (``find_closest``/``require_path``/tile shuffling instead of
    #: one-shot placement), and RESOURCE_TEMPLATES.md is explicit that the
    #: modern equivalent *replaces* this rather than stacking with it.
    tight_resource_backstop: bool = False

    #: System A configuration. Ignored on the legacy path.
    pins: ThemePins = field(default_factory=ThemePins)
    flavor: ResourceFlavor = field(default_factory=ResourceFlavor)


#: Per-biome role pins. These pick which *skin* each resource role wears,
#: which is cosmetic - but pinning them at all is not, because it stops
#: ``themes.inc`` re-rolling the skins on every generation.
BIOME_PINS: dict[str, ThemePins] = {
    "temperate": ThemePins(
        theme="PALAEARCTIC_EUROPE_TEMPERATE",
        straggler_tree=349,  # TREE_OAK
    ),
    "arid": ThemePins(
        theme="PALAEARCTIC_MIDDLE_EAST_DESERT",
        straggler_tree=351,   # TREE_PALM
        huntable=1796,        # Gazelle
    ),
    "desert": ThemePins(
        theme="AFROTROPICAL_DESERT",
        straggler_tree=351,   # TREE_PALM
        huntable=1796,        # Gazelle
        lureable=822,         # Javelina
    ),
    "tropical": ThemePins(
        theme="INDOMALAYAN_TROPICAL",
        straggler_tree=414,   # TREE_JUNGLE
        forage_plant=2599,    # Papaya Tree
        herdable=1142,        # Water Buffalo
    ),
    "arctic": ThemePins(
        theme="PALAEARCTIC_EUROPE_TAIGA",
        straggler_tree=413,   # TREE_PINE_SNOW
        water_preset="WATER_POND",
    ),
}

BIOME_RMS: dict[str, RmsOptions] = {
    "temperate": RmsOptions(pins=BIOME_PINS["temperate"]),
    "arid": RmsOptions(land="DIRT", land_alt="DIRT3", land_alt2="GRASS3",
                       forest="PALM_DESERT", tree="PALMTREE", forest_percent=5,
                       pins=BIOME_PINS["arid"]),
    "desert": RmsOptions(land="DESERT", land_alt="DIRT", land_alt2="DIRT3",
                         forest="PALM_DESERT", tree="PALMTREE", forest_percent=4,
                         pins=BIOME_PINS["desert"]),
    "tropical": RmsOptions(land="GRASS2", land_alt="GRASS", land_alt2="GRASS3",
                           forest="JUNGLE", tree="JUNGLETREE", forest_percent=16,
                           pins=BIOME_PINS["tropical"]),
    "arctic": RmsOptions(land="SNOW", land_alt="GRASS_SNOW", land_alt2="DIRT_SNOW",
                         forest="SNOW_FOREST", tree="PINETREE", forest_percent=10,
                         pins=BIOME_PINS["arctic"]),
}


def build_rms(
    title: str,
    projection: str,
    size: int,
    land_section: str,
    opts: RmsOptions | None = None,
    ai_map_type: str = "COASTAL",
    system_a: bool = True,
) -> str:
    """Render a complete, self-contained random map script.

    ``system_a`` selects the modern resource layer (``rms_objects``) over
    the 1999 ``land_and_water_resources.inc`` one. It is a parameter rather
    than a straight replacement purely so the two can be captured
    back-to-back in the engine and compared on the same window and seed -
    per ``CLAUDE.md``, that comparison is the thing that decides, not a
    reading of the include files. The legacy path is not intended to ship.
    """
    opts = opts or RmsOptions()
    if system_a:
        return _build_rms_system_a(title, projection, size, land_section,
                                   opts, ai_map_type)
    parts = [
        _HEADER.format(title=title, projection=projection, size=size,
                       ai_map_type=ai_map_type)
        + _LEGACY_PLAYER_SETUP.format(ai_map_type=ai_map_type),
        land_section,
        _WATER,
        _LAND_TERRAIN.format(
            land=opts.land,
            land_alt=opts.land_alt,
            land_alt2=opts.land_alt2,
            forest=opts.forest,
            forest_percent=opts.forest_percent,
            forest_clumps=opts.forest_clumps,
        ),
    ]
    if opts.elevation:
        parts.append(
            _ELEVATION.format(
                land=opts.land,
                max_elevation=opts.max_elevation,
                elevation_clumps=opts.elevation_clumps,
                elevation_tiles=opts.elevation_tiles,
            )
        )
    parts.append(_OBJECTS.format(tree=opts.tree))
    if opts.tight_resource_backstop:
        parts.append(_TIGHT_RESOURCE_BACKSTOP)
    return "\n".join(parts)


def _build_rms_system_a(
    title: str,
    projection: str,
    size: int,
    land_section: str,
    opts: RmsOptions,
    ai_map_type: str,
) -> str:
    """Same map, resources built the way the current stock maps build them.

    Section order follows Thames: pins and theme/constant includes above
    ``<PLAYER_SETUP>``, then land, terrain, elevation, objects.
    """
    parts = [
        _HEADER.format(title=title, projection=projection, size=size,
                       ai_map_type=ai_map_type),
        build_prelude(opts.pins),
        build_player_setup(opts.pins, ai_map_type),
        land_section,
        _WATER,
        _LAND_TERRAIN.format(
            land=opts.land,
            land_alt=opts.land_alt,
            land_alt2=opts.land_alt2,
            forest=opts.forest,
            forest_percent=opts.forest_percent,
            forest_clumps=opts.forest_clumps,
        ),
    ]
    if opts.elevation:
        parts.append(
            _ELEVATION.format(
                land=opts.land,
                max_elevation=opts.max_elevation,
                elevation_clumps=opts.elevation_clumps,
                elevation_tiles=opts.elevation_tiles,
            )
        )
    parts.append(build_objects(opts.flavor))
    return "\n".join(parts)


def write_rms(path: str | Path, text: str) -> Path:
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    # The engine's parser wants plain ASCII with unix line endings.
    path.write_text(text, encoding="ascii", newline="\n")
    return path
