"""Real-engine capture pass over stock (non-rwmaps) DE random map scripts -
Arabia, Arena, Capricious - so their gold/stone/wood totals and per-player
distributions can be compared directly against our own regions on the same
metric (see resource_report.py / analysis.resource_ownership).

Reuses the exact same slot-swap + click_sequence mechanics as mod_capture.py
(same SLOT_PATH, same button coordinates, same ui_driver.ps1) - the only
difference is the source .rms comes straight from the game's own install
directory instead of being generated by `rwmaps`. The Scenario Editor
compiles whatever text sits at SLOT_PATH when "Generate Map" is clicked, so
swapping in a stock script's exact bytes works the same way as swapping in
one of ours.

Usage:
    uv run python automation/capture_stock_maps.py --run-id first_pass
    uv run python automation/capture_stock_maps.py --run-id first_pass --maps Arena
"""

from __future__ import annotations

import argparse
import shutil
import sys
import time
from pathlib import Path

sys.stdout.reconfigure(encoding="utf-8", errors="replace")
sys.stderr.reconfigure(encoding="utf-8", errors="replace")

REPO = Path(__file__).parent.parent
sys.path.insert(0, str(REPO / "src"))
sys.path.insert(0, str(Path(__file__).parent))

from rwmaps import install as install_mod  # noqa: E402
from mod_capture import newest_scenario  # noqa: E402
from tuning_matrix import (  # noqa: E402
    CANCEL_BTN,
    GENERATE_BTN,
    MENU_BTN,
    SAVE_BTN,
    UI_DRIVER,
)

SLOT_PATH = install_mod.scripts_dir() / "AA_rw_placeholder_tester.rms"

#: Stock scripts (Arena especially) are visibly slower to generate than our
#: own simple ones - mod_capture.py's click_sequence polls the Seed box for
#: only ~1.5s total (10 attempts x 150ms) before giving up, which is tuned
#: for our scripts and isn't enough headroom here. Bump both the attempt
#: count and the per-attempt poll interval so a slow real generation still
#: gets seen as a seed change instead of being reported as a dead click.
def click_sequence(before_mtime: float, max_attempts: int = 30, poll_ms: int = 1000):
    import math
    import subprocess

    scenario_dir = install_mod.find_profile() / "resources" / "_common" / "scenario"
    ps = f"""
. "{UI_DRIVER}"
Reset-IfMenuStuck {CANCEL_BTN[0]} {CANCEL_BTN[1]}
$ok = Click-GenerateMapVerified {GENERATE_BTN[0]} {GENERATE_BTN[1]} {max_attempts} {poll_ms}
if (-not $ok) {{ exit 1 }}
Click-At {MENU_BTN[0]} {MENU_BTN[1]}
Start-Sleep -Milliseconds 200
$beforeTime = [DateTimeOffset]::FromUnixTimeMilliseconds({math.ceil(before_mtime * 1000) + 200}).LocalDateTime
$ok = Click-SaveVerified {SAVE_BTN[0]} {SAVE_BTN[1]} {MENU_BTN[0]} {MENU_BTN[1]} "{scenario_dir}" $beforeTime
if (-not $ok) {{ exit 2 }}
"""
    result = subprocess.run(["powershell.exe", "-NoProfile", "-Command", ps], capture_output=True, text=True)
    print(result.stdout.strip())
    if result.returncode == 1:
        raise RuntimeError(f"Generate Map never registered a seed change:\n{result.stdout}\n{result.stderr}")
    if result.returncode == 2:
        raise RuntimeError(f"Save never closed the Menu:\n{result.stdout}\n{result.stderr}")
    if result.returncode != 0:
        raise RuntimeError(f"click sequence failed unexpectedly:\n{result.stdout}\n{result.stderr}")

#: Source .rms for each stock map - found under the game's own DRS include
#: dir (loose .rms files sit alongside the compiled DRS archives there).
GAME_RMS_DIR = Path(
    r"C:\Program Files (x86)\Steam\steamapps\common\AoE2DE\resources\_common\drs\gamedata_x2"
)
STOCK_MAPS = {
    "Arabia": GAME_RMS_DIR / "Arabia.rms",
    "Arena": GAME_RMS_DIR / "Arena.rms",
    "Capricious": GAME_RMS_DIR / "Capricious.rms",
}

N_SAMPLES = 10


def already_done(region_dir: Path) -> int:
    raw = region_dir / "raw"
    if not raw.exists():
        return 0
    return len(list(raw.glob("sample_*.aoe2scenario")))


def parse_args():
    p = argparse.ArgumentParser()
    p.add_argument("--run-id", required=True)
    p.add_argument("--n-samples", type=int, default=N_SAMPLES)
    p.add_argument("--maps", default=None,
                    help="comma-separated subset of STOCK_MAPS keys (default: all)")
    return p.parse_args()


def main():
    args = parse_args()
    maps = STOCK_MAPS
    if args.maps:
        wanted = {m.strip() for m in args.maps.split(",")}
        missing = wanted - set(STOCK_MAPS)
        if missing:
            raise SystemExit(f"unknown map(s): {missing}")
        maps = {k: v for k, v in STOCK_MAPS.items() if k in wanted}

    outroot = REPO / "out" / "stock_maps" / args.run_id
    outroot.mkdir(parents=True, exist_ok=True)
    t_start = time.time()

    for map_i, (name, src) in enumerate(maps.items(), 1):
        if not src.exists():
            print(f"[map {map_i}/{len(maps)}] {name}: SOURCE MISSING at {src}, skipping")
            continue

        region_dir = outroot / name
        done = already_done(region_dir)
        if done >= args.n_samples:
            print(f"[map {map_i}/{len(maps)}] {name}: already have {done}/{args.n_samples}, skipping")
            continue

        print(f"\n[map {map_i}/{len(maps)}] {name} (elapsed {time.time()-t_start:.0f}s)")
        shutil.copyfile(src, SLOT_PATH)

        archive_dir = region_dir / "raw"
        archive_dir.mkdir(parents=True, exist_ok=True)
        for sample_i in range(done, args.n_samples):
            t1 = time.time()
            before = newest_scenario()
            before_mtime = before.stat().st_mtime if before else 0
            try:
                click_sequence(before_mtime)
            except Exception as e:
                print(f"  sample {sample_i}: capture FAILED ({e})")
                continue
            after = newest_scenario()
            if after is None or after.stat().st_mtime <= before_mtime:
                print(f"  sample {sample_i}: no new file, skipping")
                continue
            dest = archive_dir / f"sample_{sample_i:03d}.aoe2scenario"
            shutil.copyfile(after, dest)
            print(f"  sample {sample_i}: captured in {time.time()-t1:.1f}s -> {dest}")

    print(f"\nDONE in {time.time()-t_start:.0f}s -> {outroot}")


if __name__ == "__main__":
    main()
